#!/bin/bash

# Loop through all subdirectories in the current directory
for dir in */; do
    if [ -d "$dir" ]; then
        # Set execute permission for owner, group owner, and others
        chmod o+x,g+x,u+x "$dir"
    fi
done
